

const PRODUCTION = process.env.NODE_ENV == "production"
const ACCESS_TOKEN_LIFESPAN=3600
const CURRENCY_CACHE_DURATION=3600
const LINE_ITEM_EXPIRATION=3600


export {
  PRODUCTION,
  CURRENCY_CACHE_DURATION,
  ACCESS_TOKEN_LIFESPAN,
  LINE_ITEM_EXPIRATION
}